version: "3.9"

services:
    # Master Node 1
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03,es04,es05
            - cluster.initial_master_nodes=es01,es02
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=false
            - node.roles=master,data_hot,data_content
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata01:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            - esnet

    # Master Node 2
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03,es04,es05
            - cluster.initial_master_nodes=es01,es02
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=false
            - node.roles=master,data_hot,data_content
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata02:/usr/share/elasticsearch/data
        networks:
            - esnet

    # Data Node 1
    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02,es04,es05
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=false
            - node.roles=data_hot,data_content
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata03:/usr/share/elasticsearch/data
        networks:
            - esnet

    # Ingest Node
    es04:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        container_name: es04
        environment:
            - node.name=es04
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02,es03,es05
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=false
            - node.roles=ingest
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata04:/usr/share/elasticsearch/data
        networks:
            - esnet

    # Coordinator Node
    es05:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
        container_name: es05
        environment:
            - node.name=es05
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02,es03,es04
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=false
            - node.roles=[] # coordinator-only
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - esnet

    # Kibana (talks to coordinator)
    kibana:
        image: docker.elastic.co/kibana/kibana:8.15.3
        container_name: kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://es05:9200
        depends_on:
            - es05
        ports:
            - "5601:5601"
        networks:
            - esnet

volumes:
    esdata01:
    esdata02:
    esdata03:
    esdata04:

networks:
    esnet:
        driver: bridge
